### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Hachiiki** [naveenpoddar/uptimer#2]
/home/runner/uptimer/fetchProjects.js:42
      client.channels.cache.get(error_logs)?.send(embed);
                                            ^

SyntaxError: Unexpected token '.'

**Comment by naveenpoddar** [comment]
Optional chaining (?.) was added in Node version 14 make sure you are using node version 14 or up

**If you are using repl.it or glitch it wont work because glitch and repl.it by default only supports node v12**
Consider using a hosting provider that supports Node 14
